-- return {
--   {
--     'kiyoon/jupynium.nvim',
--     build = 'pip3 install --user .',
--     -- Alternative Build-Optionen:
--     -- build = "uv pip install . --python=$HOME/.virtualenvs/jupynium/bin/python",
--     -- build = "conda run --no-capture-output -n jupynium pip install .",
--   },
--   {
--     'rcarriga/nvim-notify', -- optional
--   },
--   {
--     'stevearc/dressing.nvim', -- optional, UI für :JupyniumKernelSelect
--   },
-- }
